# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_0/nand_soc_axi_gpio_0_0.xci
# IP: The module: 'nand_soc_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_0/nand_soc_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'nand_soc_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_0/nand_soc_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nand_soc_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_0/nand_soc_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'nand_soc_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_0/nand_soc_axi_gpio_0_0.xci
# IP: The module: 'nand_soc_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_0/nand_soc_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'nand_soc_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_0/nand_soc_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nand_soc_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_0/nand_soc_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'nand_soc_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
