# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons.xdc

# Block Designs: bd/nand_zync_sys/nand_zync_sys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_zync_sys || ORIG_REF_NAME==nand_zync_sys} -quiet] -quiet

# IP: bd/nand_zync_sys/ip/nand_zync_sys_processing_system7_0_0/nand_zync_sys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_zync_sys_processing_system7_0_0 || ORIG_REF_NAME==nand_zync_sys_processing_system7_0_0} -quiet] -quiet

# IP: bd/nand_zync_sys/ip/nand_zync_sys_and_gate_0_0/nand_zync_sys_and_gate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_zync_sys_and_gate_0_0 || ORIG_REF_NAME==nand_zync_sys_and_gate_0_0} -quiet] -quiet

# IP: bd/nand_zync_sys/ip/nand_zync_sys_axi_gpio_0_0/nand_zync_sys_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_zync_sys_axi_gpio_0_0 || ORIG_REF_NAME==nand_zync_sys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/nand_zync_sys/ip/nand_zync_sys_axi_gpio_1_0/nand_zync_sys_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_zync_sys_axi_gpio_1_0 || ORIG_REF_NAME==nand_zync_sys_axi_gpio_1_0} -quiet] -quiet

# IP: bd/nand_zync_sys/ip/nand_zync_sys_ps7_0_axi_periph_0/nand_zync_sys_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_zync_sys_ps7_0_axi_periph_0 || ORIG_REF_NAME==nand_zync_sys_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/nand_zync_sys/ip/nand_zync_sys_rst_ps7_0_100M_0/nand_zync_sys_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_zync_sys_rst_ps7_0_100M_0 || ORIG_REF_NAME==nand_zync_sys_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/nand_zync_sys/ip/nand_zync_sys_xbar_0/nand_zync_sys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_zync_sys_xbar_0 || ORIG_REF_NAME==nand_zync_sys_xbar_0} -quiet] -quiet

# IP: bd/nand_zync_sys/ip/nand_zync_sys_auto_pc_0/nand_zync_sys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_zync_sys_auto_pc_0 || ORIG_REF_NAME==nand_zync_sys_auto_pc_0} -quiet] -quiet

# XDC: bd/nand_zync_sys/nand_zync_sys_ooc.xdc
