# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons.xdc

# Block Designs: bd/nand_soc/nand_soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_soc || ORIG_REF_NAME==nand_soc} -quiet] -quiet

# IP: bd/nand_soc/ip/nand_soc_processing_system7_0_0/nand_soc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_soc_processing_system7_0_0 || ORIG_REF_NAME==nand_soc_processing_system7_0_0} -quiet] -quiet

# IP: bd/nand_soc/ip/nand_soc_and_gate_0_0/nand_soc_and_gate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_soc_and_gate_0_0 || ORIG_REF_NAME==nand_soc_and_gate_0_0} -quiet] -quiet

# IP: bd/nand_soc/ip/nand_soc_axi_gpio_0_0/nand_soc_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_soc_axi_gpio_0_0 || ORIG_REF_NAME==nand_soc_axi_gpio_0_0} -quiet] -quiet

# IP: bd/nand_soc/ip/nand_soc_axi_gpio_0_1/nand_soc_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_soc_axi_gpio_0_1 || ORIG_REF_NAME==nand_soc_axi_gpio_0_1} -quiet] -quiet

# IP: bd/nand_soc/ip/nand_soc_ps7_0_axi_periph_0/nand_soc_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_soc_ps7_0_axi_periph_0 || ORIG_REF_NAME==nand_soc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/nand_soc/ip/nand_soc_rst_ps7_0_50M_0/nand_soc_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_soc_rst_ps7_0_50M_0 || ORIG_REF_NAME==nand_soc_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/nand_soc/ip/nand_soc_xbar_0/nand_soc_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_soc_xbar_0 || ORIG_REF_NAME==nand_soc_xbar_0} -quiet] -quiet

# IP: bd/nand_soc/ip/nand_soc_auto_pc_0/nand_soc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nand_soc_auto_pc_0 || ORIG_REF_NAME==nand_soc_auto_pc_0} -quiet] -quiet

# XDC: bd/nand_soc/nand_soc_ooc.xdc
