# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.cache/wt [current_project]
set_property parent.project_path C:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/hdl/nand_soc_wrapper.v
add_files C:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/nand_soc.bd
set_property used_in_implementation false [get_files -all c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_processing_system7_0_0/nand_soc_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_0/nand_soc_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_0/nand_soc_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_0/nand_soc_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_1/nand_soc_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_1/nand_soc_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_axi_gpio_0_1/nand_soc_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_rst_ps7_0_50M_0/nand_soc_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_rst_ps7_0_50M_0/nand_soc_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_rst_ps7_0_50M_0/nand_soc_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_xbar_0/nand_soc_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/ip/nand_soc_auto_pc_0/nand_soc_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/sources_1/bd/nand_soc/nand_soc_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files C:/Users/johns/Desktop/tasks/ADI/adi_training_summer_2026/fpga_labs/Assignment_2/project_2/project_2.srcs/constrs_1/new/cons.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top nand_soc_wrapper -part xc7z020clg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef nand_soc_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file nand_soc_wrapper_utilization_synth.rpt -pb nand_soc_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
