# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work -sv -timescale 1ns/1ps -mfcu +acc  /mnt/c/ADI/adi_training_summer_2026/Cocotb/sim/../rtl/ALU.sv
vsim  -onfinish exit -pli /home/mostafa/.local/share/pipx/venvs/cocotb/lib/python3.12/site-packages/cocotb/libs/libcocotbvpi_modelsim.so   work.ALU 
onbreak resume
run -all
quit
