// Auto-generated top-level integration module
// Generated by Verilog Module Integrator
module spi_slave_wrapper (
    input  SCLK,
    input  rst_n,
    input  CSB,
    input  SDI,
    output SDO
);

    // Internal interconnect
    wire wr_en;
    wire [14:0] addr;
    wire [7:0] wr_data;
    wire [7:0] rd_data;

    // Module instances
    reg_map u_reg_map (
        .SCLK(SCLK),
        .rst_n(rst_n),
        .wr_en(wr_en),
        .addr(addr),
        .wr_data(wr_data),
        .rd_data(rd_data)
    );

    spi_slave u_spi_slave (
        .SCLK(SCLK),
        .rst_n(rst_n),
        .CSB(CSB),
        .SDI(SDI),
        .SDO(SDO),
        .addr(addr),
        .wr_data(wr_data),
        .wr_en(wr_en),
        .rd_data(rd_data)
    );

endmodule
